default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'agriculture' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'agriculture_test' %>

production: &production
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'agriculture' %>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

cable:
  <<: *production

queue:
  <<: *production

cache:
  <<: *production
